---
channel: stable
addons:
  homer:
    repository: brenner-tobias/addon-cloudflared
    target: homer
    image: b4bz/homer
  heimdall:
    repository: Energielulu83852/home-assistant-addons/heimdall
    target: heimdall
    image: lscr.io/linuxserver/heimdall
