---
channel: stable
addons:
  dashy:
    repository: BenoitAnastay/dashy-home-assistant-addon
    target: dashy
    image: lissy93/dashy
  homer:
    repository: BenoitAnastay/homer-home-assistant-addon
    target: homer
    image: b4bz/homer
