name: Heimdall
version: latest
slug: heimdall
url: https://heimdall.site/
init: false
description: Heimdall is a way to organise all those links to your most used web sites and web applications in a simple way.
webui: http://[HOST]:[PORT:80]
stage: experimental
arch:
- aarch64
- amd64
- armv7
startup: services
ports:
  80/tcp: 80
ports_description:
  80/tcp: Web interface
map:
- share:rw
image: lscr.io/linuxserver/heimdall