name: Homer
version: latest
slug: homer
url: https://homer-demo.netlify.app/
init: false
description: Homer is a full static html/js dashboard, based on a simple yaml configuration file
webui: http://[HOST]:[PORT:8080]
stage: experimental
arch:
- aarch64
- amd64
- armv7
startup: services
ports:
  8080/tcp: 8000
ports_description:
  8080/tcp: Web interface
map:
- share:rw
image: b4bz/homer